### PR TITLE
Ask cowsay for available modules instead of making assumptions

### LINKED ISSUE #1: cowfortune fails at random times due to wrong assumptions of available cowsay modules
Cowfortune makes some assumptions about the content (see 1) and the location (see 2) of the `/usr/share/cows` folder.

1.) this line tries to detect the available cowsay modules:
https://github.com/anthraxx/cowfortune/blob/baa36aef4e5edadd790fc21c210fa96c85b15544/cowfortune.sh#L34
When there are other files in the module folder than `.cow`, cowfortune tries sometimes to use those.
For example when there is a `.pm` file, cowfortune tries to use this filename as module for cowsay.

A wrong cow-module will lead to failing cowsay and therefore cowfortune:
```
cowsay: Can't locate Acme/Cow.pm in @INC (you may need to install the Acme::Cow module) (@INC contains: /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/perl5/core_perl) at /usr/share/cows/Stegosaurus.pm line 3, <STDIN> line 1.
BEGIN failed--compilation aborted at /usr/share/cows/Stegosaurus.pm line 3, <STDIN> line 1.
```

2.) 
It seems like the location of the cow-modules has changed (or is distro dependent?)
At least under arch linux, this path is wrong:
https://github.com/anthraxx/cowfortune/blob/baa36aef4e5edadd790fc21c210fa96c85b15544/cowfortune.sh#L8

---

**As solution for both, I recommend to "ask" cowsay for its available modules, instead of making assumptions.**
`cowsay -l`

Pull request incoming.

### PR DESCRIPTION
**Pull request by UweKrause**
Fixes #1

### CODE REVIEW

**Comment by fwsmit** [comment]
Can confirm this fixes it. @anthraxx would you mind merging this?

**Comment by JasterV** [comment]
@UweKrause @fwsmit any updates on this? It is August 2022 and this stills open hahah I just experienced the error now and I just came here looking for a PR that was fixing it, and this is it

**Comment by fwsmit** [comment]
I'm unable to merge it. You'll have to ask the maintainer, who is inactive I think

**Comment by anthraxx** [comment]
Not really a high volume project so I forgot about it having any open issues :cat: 

I'll merge and release latest during this weekend. Thanks for the bump

**Pull request merged**
